### ISSUE TITLE
Support for Module API?

### ISSUE THREAD

**Issue by kiwi-josh** [romulomachado/sublime-ember-snippets#1]
Great work on the addon!

Just wondering, are you planning on supporting the [javascript module api](https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md) syntax? (Given the fact that this is the direction ember is heading)

**Comment by romulomachado** [comment]
@wytlytningNZ It's coming up next! 😄

**Comment by romulomachado** [comment]
@wytlytningNZ Just added the support! All modules included on `atom-ember-snippets` are now available here! :tada:

**Comment by kiwi-josh** [comment]
Just downloaded! thanks heaps @romulomachado
